ALTER TABLE jobs ADD COLUMN input_json TEXT;
ALTER TABLE jobs ADD COLUMN stage_counters TEXT;
ALTER TABLE jobs ADD COLUMN retryable INTEGER NOT NULL DEFAULT 1;

ALTER TABLE scans ADD COLUMN job_id TEXT REFERENCES jobs(id) ON DELETE SET NULL;
ALTER TABLE scans ADD COLUMN mapping_pairs_checked INTEGER NOT NULL DEFAULT 0;
ALTER TABLE scans ADD COLUMN cache_hits INTEGER NOT NULL DEFAULT 0;
ALTER TABLE scans ADD COLUMN prompt_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE scans ADD COLUMN completion_tokens INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_scans_job ON scans(job_id);
